from gor4 import GOR4

g = GOR4('DATABASE/New_KS.267.seq', 'DATABASE/New_KS.267.obs')
print 'DKATIPSESPFAAAEVADGAIVVDIAKMKYETPELHVKVGDTVTWINREA'
pred, prob = g.predict('DKATIPSESPFAAAEVADGAIVVDIAKMKYETPELHVKVGDTVTWINREA')

print pred
print prob
