from gor_iv import GOR_IV

g = GOR_IV('DATABASE/New_KS.267.seq', 'DATABASE/New_KS.267.obs')
print 'DKATIPSESPFAAAEVADGAIVVDIAKMKYETPELHVKVGDTVTWINREA'
pred, prob = g.predict('DKATIPSESPFAAAEVADGAIVVDIAKMKYETPELHVKVGDTVTWINREA')

print pred
print prob
