SAMPLE_DATA = {
    'genomes':
    {
        'NC_030446.1':
        {
            'id': ('NC_030446.1 Tibetan frog hepatitis B virus isolate '
                   '243398, complete genome'),
            'genome': (
                'CAGTAGTTATTACGGAAACTATTGTTGTTTGATTATCATGTACTGCCTGTAATTCCATG'
                'GATCCTATTGTTAGATTTTCTTTGCAATTAGTCGAAAACTTACCTGATGATTATTTTCC'
                'TGACAATGATCAATTTTTGAGGCATGCATTTGATGTGGCACACCTGTATTGGGAAGATG'
                'CTGAAAATAAAACTTACCATGTTCAAACTTCTCGTTCAATCTATGAAGTTATCCTCATC'
                'TTAAGAACTGTCCCCCCTTTGTTGGGATTCACTCACAGACAGTTGAGGGAACATTGGGA'
                'ATACCTCAGAGATCAGGAAAATTGGGGAAACCAAACACCTCCTCCATATCCCCTTCCTG'
                'AGTTGCCTCATTCTTTCCCTGTGTCCATTAGGGACCCACCATTGCTTACTCAGTTCCAA'
                'GCTATCACTGATAGACACCGAGAGCTGAGAGGTGCAGTAAATGTGGGTCAACCTAATTC'
                'TTACAGGGAACTGTGGATGCTCTCAGAATTCAACAGATTCTTGGGGATTATGTTAGAGT'
                'CACAAACACGGTTTCTAATAAAAAGACTCTGGTATCACATAAACTGTATTGCCTGGGGA'
                'GAAGCCACTGTCCACAACCACGTAGCTAAGGTAAGAACTTGGTTGGCTACGCCAGCCCC'
                'ATACAGGGGTCAAAACGCTCCCCTTATTGAAGAGATTGTGGAGCCGCAACGTCAGAGGA'
                'CGTCCAGGCCCAATTCTAGAAGAGCTAGAGGGGGCTCTCACCCAGGCGGGGACAGAGGA'
                'CTATATTATCAGAGGACAGTCAGGAGATTTAATAGTCCAAGGGAAAGAGGATCTAGACG'
                'GAGGAGTCCTTCCCCTGCAGGCAGAACCTGAACGCCTGTTAGGACCATTGAAGGGACTC'
                'TATCAAAATGACGTTCCCCCCTTCAATCCGTCTTGGGAGATCCCTACCATTCAAGGGGT'
                'ACACCTTCAAGAAGATATTATCAGAGAGATTCCCGATAGGAGATGGGCTTACATTTACC'
                'CAATTAGGTTTTGGCCAAACGAGGTTAAATACCGCCCCCGGGAACAAGGAATCACAGAT'
                'AAATACCCCGAACATACCAGAGCACATTCAGAAAAAGTCTCCCTCTACTTGCAGACATT'
                'ATATAACAATGGGATCTTATACAAAAGGGAATCCAGGCATGTGCTTTTATTCAATGATA'
                'ATCCTTACAGCTGGGAGTCTAATAATCTACTGCCCTGCCACTGCCATAAAAGCCAGGAC'
                'TACGAGGGCCTCGGAAGGCAGCCACCGAGCAGACGGAGCAATGAGGTTCTTCGCCCGAG'
                'TGTGGAGTTGGATAGGGGGAAACCCCTCACAACACGTCTCAGCCCAAGAGCACAGAGAC'
                'CGGATGGAAGACCCTCACGCTTTCCAGCAATACTTAGCAACCCTGCCGGACATCAACCG'
                'AGCGGCATTGTTAAGTTTAAACAAACACTTCCGGCTGGACAATCACCAAGGATTTCTAC'
                'AGATACTAGACAATGCCACGTTCGCGGAAATAGCAGAACATTATTACAGATTCCGCCAA'
                'GCATATGCCAACCACAGCATAACATGGACTCCTCCCCACGAGGAGGAATACTGGGAGGA'
                'ACACGCCCTTTATCCCGAGAAGGCGGCTCCGGTAGAACCTATCATACCGGTTCCCGGGC'
                'CCAAAAGAGCTCCTCCTCTAAAGCCACGTCCTCAACCCCGAAACAGGACAAAGCTCAGG'
                'AAGCCATCAGACGCCATACCTGTGCTGCTCGCAATTCCTACCAGCAGCTCAACAGAAGT'
                'AGGCCGGCTTCCATATCAAATCTACCCCCACGAGTTACTACCTATCCCGAAGCTGGAAG'
                'AAAAGAGTACAACTGCAAACATGAGCGGCGCTGTTTCTCCCGCTCTGTGGTTCCCAGTG'
                'GTTGCACTGGTCGTGTATTTCTTGTTAACAAAAGCTCGGGAAATTCTAGCCAAGCTAGA'
                'TTGGTGGTGGACTTCTCACAGTTTTCGAGGGGCAAACGGCGAGTGCATTTTCCAAGATA'
                'CTTCTCCCCAAACACAGAAGCACTTAGCAGGATTTTGCCCCCTCACATGTGGAGGATTT'
                'CTCTGGACCTCGCTGAGGCTTTTTACCATTTGCCTTATCATACTTCTAGCAGTCTGCGG'
                'CTATCTGTTTCTGATGGAAAAAGGGTTTACCTCTTTAGGCGAGCAGCTATGGGAGTTGG'
                'GCTCAGCCCCTGGAACCTTACTCTCTTCACTTCTATCATCGCTGAAAGGATCAGGAAAT'
                'ATTTTTCTATCCATTGCTTTGCTTACATGGATGACTTCATCTTATCTCACCCTAACCCC'
                'CGCTACCTCATTGCTGCTGCTAACGGGGTTGTGGGCTACTTACAACAATATGGGGTCAG'
                'GATAAACTTTGACAAATCTACACTAACCCCCACCAGACAAATTGTGTTTATGGGACTTC'
                'AAATAACACCCACACACATACATGTCACCAAAGAAAAGTTCCAGAAGCTTCATGATTTA'
                'TTAACTTCAATCAACACCGACGTCTTCTATGATTGGAAAATTCTTCAAAGATTTGCTGG'
                'ACATTTTAATCAGATTGTTGCTTTCTCATTGTTTGGGTCACATATTCTAGGACCCATAT'
                'ATTTAGCTATCACTAACAAAGCTGATTTTTGTTTTACTAAATCATATGTAACTGACCTG'
                'AGATATGTATTGAACCATGTCTATGATTTGAGACTCAGGGCTTCCCCCAAACACATTGT'
                'ACCATCTGTAGCAGCTGACGCTACACTTACACATGGGGGAATTGCTACTCGACAGGGAG'
                'AGGAAATTCAATTGACCTTTTCTGAGCAGAGGCCGGTCCATGTTCAGGAATTGTTAATT'
                'GCCCTGGTGGCTCTTCTCTGTTTTGTACCGAAAGGGTTACTGTCTGACTCGACATTTGT'
                'GGTGCACAAACAACTTCATACTTTGCCCTATGCGTTGGCTGCAGTAGGCCATTATCTCT'
                'TAAGCCGTGCAAAGGTCACCTATGTACACACATCGCTTAACCCTGCTGACCCTGTGTCA'
                'CGCCTCCTGGCCAATCACAGCGCTCCACGCTGGCCTTTACTTGTACACACCTCCTTGGT'
                'TAAACCACTATATATACCATGGAGCCTACTCCGTTCTCCATAATTACACACCTCCTTCG'
                'GAGCACCAGGT'),
        },
        'AM282986.1':
        {
            'id': ('Hepatitis B virus (SUBTYPE ADW2), genotype A, complete '
                   'genome'),
            'genome': (
                'TTCCACTGCCTTCCACCAAGCTCTGCAGGATCCCAAAGTCAGGGGTCTGTATTTTCCTGC'
                'TGGTGGCTCCAGTTCAGGAACAGTAAACCCTGCTCCGAATATTGCCTCTCACATCTCGTC'
                'AATCTCCGCGAGGACTGGGGACCCTGTGACGAATATGGAGAACATCACATCAGGATTCCT'
                'AGGACCCCTGCTCGTGTTACAGGCGGGGTTTTTCTTGTTGACAAGAATCCTCACAATACC'
                'GCAGAGTCTAGACTCGTGGTGGACTTCTCTCAATTTTCTAGGGGGATCACCCGTGTGTCT'
                'TGGCCAAAATTCGCAGTCCCCAACCTCCAATCACTCACCAACCTCCTGTCCTCCAATTTG'
                'TCCTGGTTATCGCTGGATGTGTCTGCGGCGTTTTATCATATTCCTCTTCATCCTGCTGCT'
                'ATGCCTCATCTTCTTGTTGGTTCTTCTGGATTATCAAGGTATGTTGCCCGTTTGTCCTCT'
                'AATTCCAGGAACAACAACAACCAGTACGGGACCATGCAAAACCTGCACGACTCCTGCTCA'
                'AGGCAACTCTATGTTTCCCTCATGTTGCTGTACAAAACCTTCGGATGGAAATTGCACCTG'
                'TATTCCCATCCCATCGTCTTGGGCTTTCGCAAAATACCTATGGGAGTGGGCCTCAGTCCG'
                'TTTCTCTTGGCTCAGTTTACTAGTGCCATTTGTTCAGTGGTTCGTAGGGCTTTCCCCCAC'
                'TGTTTGGCTTTCAGCTATATGGATGATGTGGTATTGGGGGCCAAGTCTGTACAGCATCGT'
                'GAGTCCCTTTATACCGCTGTTACCAATTTTCTTTTGTCTCTGGGTATACATTTAAACCCT'
                'AACAAAACAAAAAGATGGGGTTATTCCCTAAACTTCATGGGTTACATAATTGGAAGTTGG'
                'GGAACGTTGCCACAGGATCATATTGTACAAAAGATCAAACACTGTTTTAGAAAACTTCCT'
                'GTTAACAGGCCTATTGATTGGAAAGTATGTCAAAGAATTGTGGGTCTTTTGGGCTTTGCT'
                'GCTCCATTTACACAATGTGGATATCCTGCCTTAATGCCTTTGTATGCCTGTATACAAGCT'
                'AAACAGGCTTTCACTTTCTCGCCAACTTACAAGGCCTTTCTAAGTAAACAGTACATGAAC'
                'CTTTACCCCGTTGCTCGGCAACGGCCTGGTCTGTGCCAAGTGTTTGCTGACGCAACCCCC'
                'ACTGGCTGGGGCTTGGCCATAGGCCATCAGCGCATGCGTGGAACCTTTGTGGCTCCTCTG'
                'CCGATCCATACTGCGGAACTCCTAGCCGCTTGTTTTGCTCGCAGCCGGTCTGGGGCAAAG'
                'CTCATCGGAACTGACAATTCTGTCGTCCTCTCGCGGAAATATACATCGTTTCCATGGCTG'
                'CTAGGTTGTACTGCCAACTGGATCCTTCGCGGGACGTCCTTTGTTTACGTCCCGTCGGCG'
                'CTGAATCCCGCGGACGACCCCTCTCGGGGCCGCTTGGGACTCTCTCGTCCCCTTCTCCGT'
                'CTGCCGTTCCAGCCGACCACGGGGCGCACCTCTCTTTACGCGGTCTCCCCGTCTGTGCCT'
                'TCTCATCTGCCGGTCCGTGTGCACTTCGCTTCACCTCTGCACGTTGCATGGAGACCACCG'
                'TGAACGCCCATCAGATCCTGCCCAAGGTCTTACATAAGAGGACTCTTGGACTCCCAGCAA'
                'TGTCAACGACCGACCTTGAGGCCTACTTCAAAGACTGTGTGTTTAAGGACTGGGAGGAGC'
                'TGGGGGAGGAGATTAGGTTAAAGGTCTTTGTATTAGGAGGCTGTAGGCATAAATTGGTCT'
                'GCGCACCAGCACCATGCAACTTTTTCACCTCTGCCTAATCATCTCTTGTACATGTCCCAC'
                'TGTTCAAGCCTCCAAGCTGTGCCTTGGGTGGCTTTGGGGCATGGACATTGACCCTTATAA'
                'AGAATTTGGAGCTACTGTGGAGTTACTCTCGTTTTTGCCTTCTGACTTTTTTCCTTCCGT'
                'CAGAGATCTCCTAGACACCGCCTCAGCTCTGTATCGGGAAGCCTTAGAGTCTCCTGAGCA'
                'TTGCTCACCTCACCATACTGCACTCAGGCAAGCAATTCTCTGCTGGGGGGAATTGATGAC'
                'TCTAGCTACCTGGGTGGGTAATAATTTGGAAGATCCAGCATCCAGGGATCTAGTAGTCAA'
                'TTATGTTAATACTAACATGGGTTTAAAGATCAGGCAACTATTGTGGTTTCATATATCTTG'
                'CCTTACTTTTGGAAGAGAGACTGTACTTGAATATTTGGTCTCTTTCGGAGTGTGGATTCG'
                'CACTCCTCCAGCCTATAGACCACCAAATGCCCCTATCTTATCAACACTTCCGGAAACTAC'
                'TGTTGTTAGACGACGGGACCGAGGCAGGTCCCCTAGAAGAAGAACTCCCTCGCCTCGCAG'
                'ACGCAGATCTCAATCGCCGCGTCGCAGAAGATCTCAATCTCGGGAATCTCAATGTTAGTA'
                'TTCCTTGGACTCATAAGGTGGGAAACTTTACTGGGCTTTATTCCTCTACAGTACCTATCT'
                'TTAATCCTGAATGGCAAACTCCTTCCTTTCCTAAGATTCATTTACAAGAGGACATTATTA'
                'ATAGGTGTCAACAATTTGTGGGCCCTCTCACTGTAAATGAAAAGAGAAGATTGAAATTAA'
                'TTATGCCTGCTAGATTCTATCCTACCCACACTAAATATTTGCCCTTAGACAAAGGAATTA'
                'AACCTTATTATCCAGATCAGGTAGTTAATCATTACTTCAAAACCAGACATTATTTACATA'
                'CTCTTTGGAAGGCTGGTATTCTATATAAGAGGGAAACCACACGTAGCGCATCATTTTGCG'
                'GGTCACCATATTCTTGGGAACAAGAGCTACAGCATGGGAGGTTGGTCATCGAAACCTCGC'
                'AAAGGCATGGGGACGAATCTTTCTGTTCCCAACCCTCTGGGATTCTTTCCCGATCATCAG'
                'TTGGACCCTGCATTCGGAGCCAACTCAAACAATCCAGATTGGGACTTCAACCCCATCAAG'
                'GACCACTGGCCAGCAGCCAACCAGGTAGGAGTGGGAGCATTCGGGCCAGGGTTCACCCCT'
                'CCACACGGCGGTGTTTTGGGGTGGAGCCCTCAGGCTCAGGGCATATTGACCACAGTGTCA'
                'ACAATTCCTCCTCCTGCCTCCACCAATCGGCAGTCAGGAAGGCAGCCTACTCCCATCTCT'
                'CCACCTCTAAGAGACAGTCATCCTCAGGCCATGCAGTGGAA'),
        },
    },

    'proteins':
    {
        'YP_009259545.1':
        {
            'id': (
                'acc|GENBANK|YP_009259545.1|GENBANK|NC_030446.1|polymerase '
                '[Tibetan frog hepatitis B virus isolate 243398, complete '
                'genome]'),
            'protein': (
                'MKRLWSRNVRGRPGPILEELEGALTQAGTEDYIIRGQSGDLIVQ'
                'GKEDLDGGVLPLQAEPERLLGPLKGLYQNDVPPFNPSWEIPTIQGVHLQEDIIREIPD'
                'RRWAYIYPIRFWPNEVKYRPREQGITDKYPEHTRAHSEKVSLYLQTLYNNGILYKRES'
                'RHVLLFNDNPYSWESNNLLPCHCHKSQDYEGLGRQPPSRRSNEVLRPSVELDRGKPLT'
                'TRLSPRAQRPDGRPSRFPAILSNPAGHQPSGIVKFKQTLPAGQSPRISTDTRQCHVRG'
                'NSRTLLQIPPSICQPQHNMDSSPRGGILGGTRPLSREGGSGRTYHTGSRAQKSSSSKA'
                'TSSTPKQDKAQEAIRRHTCAARNSYQQLNRSRPASISNLPPRVTTYPEAGRKEYNCKH'
                'ERRCFSRSVVPSGCTGRVFLVNKSSGNSSQARLVVDFSQFSRGKRRVHFPRYFSPNTE'
                'ALSRILPPHMWRISLDLAEAFYHLPYHTSSSLRLSVSDGKRVYLFRRAAMGVGLSPWN'
                'LTLFTSIIAERIRKYFSIHCFAYMDDFILSHPNPRYLIAAANGVVGYLQQYGVRINFD'
                'KSTLTPTRQIVFMGLQITPTHIHVTKEKFQKLHDLLTSINTDVFYDWKILQRFAGHFN'
                'QIVAFSLFGSHILGPIYLAITNKADFCFTKSYVTDLRYVLNHVYDLRLRASPKHIVPS'
                'VAADATLTHGGIATRQGEEIQLTFSEQRPVHVQELLIALVALLCFVPKGLLSDSTFVV'
                'HKQLHTLPYALAAVGHYLLSRAKVTYVHTSLNPADPVSRLLANHSAPRWPLLVHTSLV'
                'KPLYIPWSLLRSP'),
            # Note that the following uses Python offsets, since these
            # numbers simulate what comes back from having BioPython parse
            # a GenBank record.
            'range': '[675:3111](+)',
        },
        'CAK55121.1':
        {
            'id': ('acc|GENBANK|CAK55121.1|GENBANK|AM282986.1|polymerase '
                   '[Hepatitis B virus subtype adw2]'),
            'protein': (
                'MPLSYQHFRKLLLLDDGTEAGPLEEELPRLADADLNRRVAEDLN'
                'LGNLNVSIPWTHKVGNFTGLYSSTVPIFNPEWQTPSFPKIHLQEDIINRCQQFVGPLT'
                'VNEKRRLKLIMPARFYPTHTKYLPLDKGIKPYYPDQVVNHYFKTRHYLHTLWKAGILY'
                'KRETTRSASFCGSPYSWEQELQHGRLVIETSQRHGDESFCSQPSGILSRSSVGPCIRS'
                'QLKQSRLGLQPHQGPLASSQPGRSGSIRARVHPSTRRCFGVEPSGSGHIDHSVNNSSS'
                'CLHQSAVRKAAYSHLSTSKRQSSSGHAVEFHCLPPSSAGSQSQGSVFSCWWLQFRNSK'
                'PCSEYCLSHLVNLREDWGPCDEYGEHHIRIPRTPARVTGGVFLVDKNPHNTAESRLVV'
                'DFSQFSRGITRVSWPKFAVPNLQSLTNLLSSNLSWLSLDVSAAFYHIPLHPAAMPHLL'
                'VGSSGLSRYVARLSSNSRNNNNQYGTMQNLHDSCSRQLYVSLMLLYKTFGWKLHLYSH'
                'PIVLGFRKIPMGVGLSPFLLAQFTSAICSVVRRAFPHCLAFSYMDDVVLGAKSVQHRE'
                'SLYTAVTNFLLSLGIHLNPNKTKRWGYSLNFMGYIIGSWGTLPQDHIVQKIKHCFRKL'
                'PVNRPIDWKVCQRIVGLLGFAAPFTQCGYPALMPLYACIQAKQAFTFSPTYKAFLSKQ'
                'YMNLYPVARQRPGLCQVFADATPTGWGLAIGHQRMRGTFVAPLPIHTAELLAACFARS'
                'RSGAKLIGTDNSVVLSRKYTSFPWLLGCTANWILRGTSFVYVPSALNPADDPSRGRLG'
                'LSRPLLRLPFQPTTGRTSLYAVSPSVPSHLPVRVHFASPLHVAWRPP'),
            # Note that the following uses Python offsets, since these
            # numbers simulate what comes back from having BioPython parse
            # a GenBank record.
            'range': 'join{[2306:3221](+), [0:1623](+)}',
        },
    }
}
