SAMPLE_DATA = {
    'genomes':
    {
        'NC_030446.1':
        {
            'id': ('NC_030446.1 Tibetan frog hepatitis B virus isolate '
                   '243398, complete genome'),
            'genome': (
                'CAGTAGTTATTACGGAAACTATTGTTGTTTGATTATCATGTACTGCCTGTAATTCCATG'
                'GATCCTATTGTTAGATTTTCTTTGCAATTAGTCGAAAACTTACCTGATGATTATTTTCC'
                'TGACAATGATCAATTTTTGAGGCATGCATTTGATGTGGCACACCTGTATTGGGAAGATG'
                'CTGAAAATAAAACTTACCATGTTCAAACTTCTCGTTCAATCTATGAAGTTATCCTCATC'
                'TTAAGAACTGTCCCCCCTTTGTTGGGATTCACTCACAGACAGTTGAGGGAACATTGGGA'
                'ATACCTCAGAGATCAGGAAAATTGGGGAAACCAAACACCTCCTCCATATCCCCTTCCTG'
                'AGTTGCCTCATTCTTTCCCTGTGTCCATTAGGGACCCACCATTGCTTACTCAGTTCCAA'
                'GCTATCACTGATAGACACCGAGAGCTGAGAGGTGCAGTAAATGTGGGTCAACCTAATTC'
                'TTACAGGGAACTGTGGATGCTCTCAGAATTCAACAGATTCTTGGGGATTATGTTAGAGT'
                'CACAAACACGGTTTCTAATAAAAAGACTCTGGTATCACATAAACTGTATTGCCTGGGGA'
                'GAAGCCACTGTCCACAACCACGTAGCTAAGGTAAGAACTTGGTTGGCTACGCCAGCCCC'
                'ATACAGGGGTCAAAACGCTCCCCTTATTGAAGAGATTGTGGAGCCGCAACGTCAGAGGA'
                'CGTCCAGGCCCAATTCTAGAAGAGCTAGAGGGGGCTCTCACCCAGGCGGGGACAGAGGA'
                'CTATATTATCAGAGGACAGTCAGGAGATTTAATAGTCCAAGGGAAAGAGGATCTAGACG'
                'GAGGAGTCCTTCCCCTGCAGGCAGAACCTGAACGCCTGTTAGGACCATTGAAGGGACTC'
                'TATCAAAATGACGTTCCCCCCTTCAATCCGTCTTGGGAGATCCCTACCATTCAAGGGGT'
                'ACACCTTCAAGAAGATATTATCAGAGAGATTCCCGATAGGAGATGGGCTTACATTTACC'
                'CAATTAGGTTTTGGCCAAACGAGGTTAAATACCGCCCCCGGGAACAAGGAATCACAGAT'
                'AAATACCCCGAACATACCAGAGCACATTCAGAAAAAGTCTCCCTCTACTTGCAGACATT'
                'ATATAACAATGGGATCTTATACAAAAGGGAATCCAGGCATGTGCTTTTATTCAATGATA'
                'ATCCTTACAGCTGGGAGTCTAATAATCTACTGCCCTGCCACTGCCATAAAAGCCAGGAC'
                'TACGAGGGCCTCGGAAGGCAGCCACCGAGCAGACGGAGCAATGAGGTTCTTCGCCCGAG'
                'TGTGGAGTTGGATAGGGGGAAACCCCTCACAACACGTCTCAGCCCAAGAGCACAGAGAC'
                'CGGATGGAAGACCCTCACGCTTTCCAGCAATACTTAGCAACCCTGCCGGACATCAACCG'
                'AGCGGCATTGTTAAGTTTAAACAAACACTTCCGGCTGGACAATCACCAAGGATTTCTAC'
                'AGATACTAGACAATGCCACGTTCGCGGAAATAGCAGAACATTATTACAGATTCCGCCAA'
                'GCATATGCCAACCACAGCATAACATGGACTCCTCCCCACGAGGAGGAATACTGGGAGGA'
                'ACACGCCCTTTATCCCGAGAAGGCGGCTCCGGTAGAACCTATCATACCGGTTCCCGGGC'
                'CCAAAAGAGCTCCTCCTCTAAAGCCACGTCCTCAACCCCGAAACAGGACAAAGCTCAGG'
                'AAGCCATCAGACGCCATACCTGTGCTGCTCGCAATTCCTACCAGCAGCTCAACAGAAGT'
                'AGGCCGGCTTCCATATCAAATCTACCCCCACGAGTTACTACCTATCCCGAAGCTGGAAG'
                'AAAAGAGTACAACTGCAAACATGAGCGGCGCTGTTTCTCCCGCTCTGTGGTTCCCAGTG'
                'GTTGCACTGGTCGTGTATTTCTTGTTAACAAAAGCTCGGGAAATTCTAGCCAAGCTAGA'
                'TTGGTGGTGGACTTCTCACAGTTTTCGAGGGGCAAACGGCGAGTGCATTTTCCAAGATA'
                'CTTCTCCCCAAACACAGAAGCACTTAGCAGGATTTTGCCCCCTCACATGTGGAGGATTT'
                'CTCTGGACCTCGCTGAGGCTTTTTACCATTTGCCTTATCATACTTCTAGCAGTCTGCGG'
                'CTATCTGTTTCTGATGGAAAAAGGGTTTACCTCTTTAGGCGAGCAGCTATGGGAGTTGG'
                'GCTCAGCCCCTGGAACCTTACTCTCTTCACTTCTATCATCGCTGAAAGGATCAGGAAAT'
                'ATTTTTCTATCCATTGCTTTGCTTACATGGATGACTTCATCTTATCTCACCCTAACCCC'
                'CGCTACCTCATTGCTGCTGCTAACGGGGTTGTGGGCTACTTACAACAATATGGGGTCAG'
                'GATAAACTTTGACAAATCTACACTAACCCCCACCAGACAAATTGTGTTTATGGGACTTC'
                'AAATAACACCCACACACATACATGTCACCAAAGAAAAGTTCCAGAAGCTTCATGATTTA'
                'TTAACTTCAATCAACACCGACGTCTTCTATGATTGGAAAATTCTTCAAAGATTTGCTGG'
                'ACATTTTAATCAGATTGTTGCTTTCTCATTGTTTGGGTCACATATTCTAGGACCCATAT'
                'ATTTAGCTATCACTAACAAAGCTGATTTTTGTTTTACTAAATCATATGTAACTGACCTG'
                'AGATATGTATTGAACCATGTCTATGATTTGAGACTCAGGGCTTCCCCCAAACACATTGT'
                'ACCATCTGTAGCAGCTGACGCTACACTTACACATGGGGGAATTGCTACTCGACAGGGAG'
                'AGGAAATTCAATTGACCTTTTCTGAGCAGAGGCCGGTCCATGTTCAGGAATTGTTAATT'
                'GCCCTGGTGGCTCTTCTCTGTTTTGTACCGAAAGGGTTACTGTCTGACTCGACATTTGT'
                'GGTGCACAAACAACTTCATACTTTGCCCTATGCGTTGGCTGCAGTAGGCCATTATCTCT'
                'TAAGCCGTGCAAAGGTCACCTATGTACACACATCGCTTAACCCTGCTGACCCTGTGTCA'
                'CGCCTCCTGGCCAATCACAGCGCTCCACGCTGGCCTTTACTTGTACACACCTCCTTGGT'
                'TAAACCACTATATATACCATGGAGCCTACTCCGTTCTCCATAATTACACACCTCCTTCG'
                'GAGCACCAGGT'),
        },
    },

    'proteins':
    {
        'YP_009259545.1':
        {
            'id': (
                'acc|GENBANK|YP_009259545.1|GENBANK|NC_030446.1|polymerase '
                '[Tibetan frog hepatitis B virus isolate 243398, complete '
                'genome]'),
            'protein': (
                'MKRLWSRNVRGRPGPILEELEGALTQAGTEDYIIRGQSGDLIVQ'
                'GKEDLDGGVLPLQAEPERLLGPLKGLYQNDVPPFNPSWEIPTIQGVHLQEDIIREIPD'
                'RRWAYIYPIRFWPNEVKYRPREQGITDKYPEHTRAHSEKVSLYLQTLYNNGILYKRES'
                'RHVLLFNDNPYSWESNNLLPCHCHKSQDYEGLGRQPPSRRSNEVLRPSVELDRGKPLT'
                'TRLSPRAQRPDGRPSRFPAILSNPAGHQPSGIVKFKQTLPAGQSPRISTDTRQCHVRG'
                'NSRTLLQIPPSICQPQHNMDSSPRGGILGGTRPLSREGGSGRTYHTGSRAQKSSSSKA'
                'TSSTPKQDKAQEAIRRHTCAARNSYQQLNRSRPASISNLPPRVTTYPEAGRKEYNCKH'
                'ERRCFSRSVVPSGCTGRVFLVNKSSGNSSQARLVVDFSQFSRGKRRVHFPRYFSPNTE'
                'ALSRILPPHMWRISLDLAEAFYHLPYHTSSSLRLSVSDGKRVYLFRRAAMGVGLSPWN'
                'LTLFTSIIAERIRKYFSIHCFAYMDDFILSHPNPRYLIAAANGVVGYLQQYGVRINFD'
                'KSTLTPTRQIVFMGLQITPTHIHVTKEKFQKLHDLLTSINTDVFYDWKILQRFAGHFN'
                'QIVAFSLFGSHILGPIYLAITNKADFCFTKSYVTDLRYVLNHVYDLRLRASPKHIVPS'
                'VAADATLTHGGIATRQGEEIQLTFSEQRPVHVQELLIALVALLCFVPKGLLSDSTFVV'
                'HKQLHTLPYALAAVGHYLLSRAKVTYVHTSLNPADPVSRLLANHSAPRWPLLVHTSLV'
                'KPLYIPWSLLRSP'),
            'range': '[676:3111](+)',
        }
    }
}
