name: Test and format

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          submodules: false
          ref: ${{ github.head_ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: nox
        run: uv run --only-group dev noxfile.py

      - name: Format Code with ruff
        run: uv run --only-group dev ruff format

      - name: Format Imports with ruff
        run: uv run --only-group dev ruff check --fix

      - name: Commit and push ruff formatting to PR
        run: |
          git pull
          if ! git diff --quiet
          then
            git commit -am "Format with ruff"
            git push
          fi
